global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
    send_resolved: true 
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      *Description:* {{ .Annotations.description }}
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
# route:
#   group_by: Backend shutdown
#   receiver: email-me

# receivers:
# - name: email-me
#   email_configs:
#   - to: rehab.sayed.abdelghany@gmail.com
#     from: rehab.sayed.abdelghany@gmail.com
#     smarthost: smtp.gmail.com:587
#     auth_username: rehab.sayed.abdelghany@gmail.com
#     auth_identity: rehab.sayed.abdelghany@gmail.com
#     auth_password: jwzvdjskgtielfyt